version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/web-project
hooks:
  BeforeInstall:
    - location: Scripts/BeforeInstall.sh
    - runas: ec2-user
  AfterInstall:
    - location: Scripts/AfterInstall.sh
    - runas: ec2-user
    - timeout: 20
